name: Testing

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel last executions
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: Retrieve repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "16.13.0"
      - name: Install dependencies
        run: npm i
      - name: Execute build
        run: npm run build
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Execute test
        run: npm test
